### ISSUE TITLE
KlipperScreen v0.2.0-59 selecting the thermometer results in "Unable to load panel temperature"

### ISSUE THREAD

**Issue by Anathema-Device** [jordanruthe/KlipperScreen#482]
KlipperScreen  v0.2.0-59 Selecting the thermometer icon on the main screen throws this error:
```
2022-01-27 20:48:37,722 [screen.py:show_panel()] - Unable to load panel temperature
Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 306, in show_panel
    self.panels[panel_name].initialize(panel_name)
  File "/home/pi/KlipperScreen/panels/temperature.py", line 33, in initialize
    self.select_heater(None, x)
  File "/home/pi/KlipperScreen/panels/temperature.py", line 179, in select_heater
    if self.devices[device]["can_target"]:
KeyError: 'extruder1'
```
I probably have an odd configuration.  There are 4 extruders defined (3 switchable hot-ends).  extruder and extruder1 are for 2-colour switching hotend where the heater is defined by extruder and extruder1 just shares it (shared heater: extruder).  extruder2 and extruder3 both define a heater and sensor.  The display showed extruder, extruder2 and extruder3 previously before I updated to this version.

**Comment by Anathema-Device** [comment]
Awesome!  Thanks @alfrix !
