### ISSUE TITLE
[BUG] Impossible to install KlipperScreen - Failed building wheel for patchelf

### ISSUE THREAD

**Issue by Guilouz** [jordanruthe/KlipperScreen#812]
**Describe the bug**
Since recent changes, impossible to install KlipperScreen manually with script (./scripts/KlipperScreen-install.sh) but working from Kiauh.

**To Reproduce**
Just run install script

```
Collecting dbus-python
  Using cached dbus-python-1.3.2.tar.gz (605 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pi/.KlipperScreen-env/bin/python /home/pi/.KlipperScreen-env/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ozqt06uu/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'meson-python>=0.8.1' 'meson>=0.60.0' ninja patchelf setuptools wheel
       cwd: None
  Complete output (184 lines):
  Collecting meson-python>=0.8.1
    Using cached meson_python-0.11.0-py3-none-any.whl (63 kB)
  Collecting meson>=0.60.0
    Using cached meson-0.64.1-py3-none-any.whl (895 kB)
  Collecting ninja
    Using cached ninja-1.11.1.tar.gz (27 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting patchelf
    Using cached patchelf-0.17.0.0.tar.gz (166 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting setuptools
    Using cached setuptools-65.6.3-py3-none-any.whl (1.2 MB)
  Collecting wheel
    Using cached wheel-0.38.4-py3-none-any.whl (36 kB)
  Collecting tomli>=1.0.0; python_version < "3.11"
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting pyproject-metadata>=0.5.0
    Using cached pyproject_metadata-0.6.1-py3-none-any.whl (7.4 kB)
  Collecting packaging>=19.0
    Using cached packaging-21.3-py3-none-any.whl (40 kB)
  Collecting pyparsing!=3.0.5,>=2.0.2
    Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
  Building wheels for collected packages: ninja, patchelf
    Building wheel for ninja (PEP 517): started
    Building wheel for ninja (PEP 517): still running...
    Building wheel for ninja (PEP 517): still running...
    Building wheel for ninja (PEP 517): still running...
    Building wheel for ninja (PEP 517): still running...
    Building wheel for ninja (PEP 517): still running...
    Building wheel for ninja (PEP 517): finished with status 'done'
    Created wheel for ninja: filename=ninja-1.11.1-cp38-cp38-linux_aarch64.whl size=129291 sha256=4c919611ef61cc808c1f9843be632adb51945fc66140973d8e34f5cb2954dca0
    Stored in directory: /home/pi/.cache/pip/wheels/b1/e5/6b/270c93a0fd0063f103f3541825579bb16906970a6a1521c715
    Building wheel for patchelf (PEP 517): started
    Building wheel for patchelf (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/pi/.KlipperScreen-env/bin/python /tmp/tmp8eyaxfc4 build_wheel /tmp/tmpyvdk83gr
         cwd: /tmp/pip-install-_g82karj/patchelf
    Complete output (131 lines):


    --------------------------------------------------------------------------------
    -- Trying "Ninja" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    Not searching for unused variables given on the command line.
    CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-install-_g82karj/patchelf/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Ninja" generator - failure
    --------------------------------------------------------------------------------



    --------------------------------------------------------------------------------
    -- Trying "Unix Makefiles" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    Not searching for unused variables given on the command line.
    -- The C compiler identification is GNU 9.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- The CXX compiler identification is GNU 9.4.0
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-_g82karj/patchelf/_cmake_test_compile/build
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Unix Makefiles" generator - success
    --------------------------------------------------------------------------------

    Configuring Project
      Working directory:
        /tmp/pip-install-_g82karj/patchelf/_skbuild/linux-aarch64-3.8/cmake-build
      Command:
        cmake /tmp/pip-install-_g82karj/patchelf -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-_g82karj/patchelf/_skbuild/linux-aarch64-3.8/cmake-install -DPYTHON_VERSION_STRING:STRING=3.8.10 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-lzpoh4k1/overlay/lib/python3.8/site-packages/skbuild/resources/cmake -DPYTHON_EXECUTABLE:PATH=/home/pi/.KlipperScreen-env/bin/python -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPYTHON_LIBRARY:PATH=/usr/lib/arm-linux-gnueabihf/libpython3.8.so -DPython_EXECUTABLE:PATH=/home/pi/.KlipperScreen-env/bin/python -DPython_ROOT_DIR:PATH=/home/pi/.KlipperScreen-env -DPython_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython_FIND_REGISTRY:STRING=NEVER -DPython3_EXECUTABLE:PATH=/home/pi/.KlipperScreen-env/bin/python -DPython3_ROOT_DIR:PATH=/home/pi/.KlipperScreen-env -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.8 -DPython3_FIND_REGISTRY:STRING=NEVER -DCMAKE_BUILD_TYPE:STRING=Release

    -- The C compiler identification is GNU 9.4.0
    -- The CXX compiler identification is GNU 9.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:

        PYTHON_EXECUTABLE
        PYTHON_INCLUDE_DIR
        PYTHON_LIBRARY
        PYTHON_VERSION_STRING
        Python3_EXECUTABLE
        Python3_FIND_REGISTRY
        Python3_INCLUDE_DIR
        Python3_ROOT_DIR
        Python_EXECUTABLE
        Python_FIND_REGISTRY
        Python_INCLUDE_DIR
        Python_ROOT_DIR
        SKBUILD


    -- Build files have been written to: /tmp/pip-install-_g82karj/patchelf/_skbuild/linux-aarch64-3.8/cmake-build
    Scanning dependencies of target build_patchelf
    [ 11%] Creating directories for 'build_patchelf'
    [ 22%] No download step for 'build_patchelf'
    [ 33%] Performing patch step for 'build_patchelf'
    ./bootstrap.sh: 2: autoreconf: not found
    make[2]: *** [CMakeFiles/build_patchelf.dir/build.make:100: build_patchelf-prefix/src/build_patchelf-stamp/build_patchelf-patch] Error 127
    make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/build_patchelf.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2
    Traceback (most recent call last):
      File "/tmp/pip-build-env-lzpoh4k1/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 640, in setup
        cmkr.make(make_args, install_target=cmake_install_target, env=env)
      File "/tmp/pip-build-env-lzpoh4k1/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 670, in make
        self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
      File "/tmp/pip-build-env-lzpoh4k1/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 701, in make_impl
        raise SKBuildError(

    An error occurred while building with CMake.
      Command:
        cmake --build . --target install --config Release --
      Install target:
        install
      Source directory:
        /tmp/pip-install-_g82karj/patchelf
      Working directory:
        /tmp/pip-install-_g82karj/patchelf/_skbuild/linux-aarch64-3.8/cmake-build
    Please check the install target is valid and see CMake's output for more information.
    ----------------------------------------
    ERROR: Failed building wheel for patchelf
  Successfully built ninja
  Failed to build patchelf
  ERROR: Could not build wheels for patchelf which use PEP 517 and cannot be installed directly
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/pi/.KlipperScreen-env/bin/python /home/pi/.KlipperScreen-env/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ozqt06uu/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'meson-python>=0.8.1' 'meson>=0.60.0' ninja patchelf setuptools wheel Check the logs for full command output.
Error: pip install exited with status code 0
Unable to install dependencies, aborting install.
```

With Kiauh :
```
Creating virtual environment
created virtual environment CPython3.8.10.final.0-32 in 524ms
  creator CPython3Posix(dest=/home/pi/.KlipperScreen-env, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, pkg_resources=latest, via=copy, app_data_dir=/home/pi/.local/share/virtualenv/seed-app-data/v1.0.1.debian.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
Collecting jinja2==3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1.tar.gz (18 kB)
Building wheels for collected packages: MarkupSafe
  Building wheel for MarkupSafe (setup.py) ... done
  Created wheel for MarkupSafe: filename=MarkupSafe-2.1.1-cp38-cp38-linux_aarch64.whl size=29437 sha256=64b8b6b04622cc2d1c56a0e293e5ebfa471c747a12ae4f92623a558530ef6eb5
  Stored in directory: /home/pi/.cache/pip/wheels/1e/4f/44/880eea76caa456b86230bdca1a0903ccf0382cd780bdae90d0
Successfully built MarkupSafe
Installing collected packages: MarkupSafe, jinja2
Successfully installed MarkupSafe-2.1.1 jinja2-3.1.2
Collecting netifaces==0.11.0
  Using cached netifaces-0.11.0.tar.gz (30 kB)
Building wheels for collected packages: netifaces
  Building wheel for netifaces (setup.py) ... done
  Created wheel for netifaces: filename=netifaces-0.11.0-cp38-cp38-linux_aarch64.whl size=39936 sha256=86da5bfd70ea914024350eea022c56c8342901a665618cd6ca7adaad442cee9c
  Stored in directory: /home/pi/.cache/pip/wheels/04/e2/b4/b811799a082cacaeff801af32c856fbefe6279ba96554d9a21
Successfully built netifaces
Installing collected packages: netifaces
Successfully installed netifaces-0.11.0
Collecting requests==2.28.1
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Installing collected packages: charset-normalizer, urllib3, certifi, idna, requests
Successfully installed certifi-2022.9.24 charset-normalizer-2.1.1 idna-3.4 requests-2.28.1 urllib3-1.26.13
Collecting websocket-client==1.4.2
  Using cached websocket_client-1.4.2-py3-none-any.whl (55 kB)
Installing collected packages: websocket-client
Successfully installed websocket-client-1.4.2
Collecting pycairo==1.21.0
  Using cached pycairo-1.21.0.tar.gz (340 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: pycairo
  Building wheel for pycairo (PEP 517) ... done
  Created wheel for pycairo: filename=pycairo-1.21.0-cp38-cp38-linux_aarch64.whl size=316107 sha256=e026e339d64b4de52e6229ebd09756cd6bff23fe2266b759e08fff37c3ce946e
  Stored in directory: /home/pi/.cache/pip/wheels/29/70/ec/35acc9bec1042aaa2f67009ae5cf615be86d335593bd5565e2
Successfully built pycairo
Installing collected packages: pycairo
Successfully installed pycairo-1.21.0
Collecting PyGObject==3.42.2
  Using cached PyGObject-3.42.2.tar.gz (719 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pycairo>=1.16.0 in ./.KlipperScreen-env/lib/python3.8/site-packages (from PyGObject==3.42.2) (1.21.0)
Building wheels for collected packages: PyGObject
  Building wheel for PyGObject (PEP 517) ... done
  Created wheel for PyGObject: filename=PyGObject-3.42.2-cp38-cp38-linux_aarch64.whl size=850528 sha256=bd461ddf61d09ebe2d8defea401ec675a28470552c5a00470c82b17ea756ae64
  Stored in directory: /home/pi/.cache/pip/wheels/90/26/09/b3693f5492298447a6e61c52ec5877f1d050709d6895300094
Successfully built PyGObject
Installing collected packages: PyGObject
Successfully installed PyGObject-3.42.2
Virtual enviroment created
Installing KlipperScreen unit file
Created symlink /etc/systemd/system/multi-user.target.wants/KlipperScreen.service → /etc/systemd/system/KlipperScreen.service.
Adding X11 Xwrapper
allowed_users=anybody
KlipperScreen was installed
Starting service...
[✓ OK] KlipperScreen successfully installed!
find: ‘’: No such file or directory
```

**Comment by alfrix** [comment]
on a pi it will install a pre-compiled binary so it works

if i force pip to build it, then i get an error of missing `libdbus-glib-1-dev` 
so it needs to be added to the installer in the misc section

as a side note i noticed while i ran the script is that the last line was being ignored on my system, this is likely caused by the while loop, but i will remove it since that was needed for Vext and it's not used anymore

**Comment by alfrix** [comment]
`sudo apt install autoconf` should resolve the issue

**Comment by Guilouz** [comment]
Thanks i will try

**Comment by Guilouz** [comment]
@alfrix Confirmed it's working. Thanks.
