### ISSUE TITLE
[BUG]KlipperScreen not shown

### ISSUE THREAD

**Issue by yhira1023** [jordanruthe/KlipperScreen#815]
Hi team!
I found "Failed to initialize window" in KlipperScreen.log
Please take investigation.

=======================
2022-11-26 22:50:50,832 [config.py:__init__()] - Configuration validated succesfuly
2022-11-26 22:50:50,833 [config.py:__init__()] - Configured printers: [
  {
    "Printer": {
      "moonraker_host": "127.0.0.1",
      "moonraker_port": "7125",
      "moonraker_api_key": ""
    }
  }
]
2022-11-26 22:50:50,883 [config.py:create_translations()] - Selected lang: None OS lang: ja_JP
2022-11-26 22:50:50,884 [screen.py:main()] - Failed to initialize window
Traceback (most recent call last):
  File "/home/boyon/KlipperScreen/screen.py", line 996, in main
    win = KlipperScreen(args, version)
  File "/home/boyon/KlipperScreen/screen.py", line 105, in __init__
    self._config = KlipperScreenConfig(configfile, self)
  File "/home/boyon/KlipperScreen/ks_includes/config.py", line 106, in __init__
    self.create_translations()
  File "/home/boyon/KlipperScreen/ks_includes/config.py", line 118, in create_translations
    self.install_language(lang)
  File "/home/boyon/KlipperScreen/ks_includes/config.py", line 129, in install_language
    if lang.startswith(language):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by alfrix** [comment]
this happened because ks is not translated to your language, i will fix the fallback to english in a couple of hours

extra: if you have time to translate KlipperScreen to japanese:
[KlipperScreen.zip](https://github.com/jordanruthe/KlipperScreen/files/10096443/KlipperScreen.zip)

**Comment by yhira1023** [comment]
Thanks!
