### ISSUE TITLE
Installation failed! `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Turbine1991** [jordanruthe/KlipperScreen#820]
**Describe the bug**
I've successfully installed KlipperScreen on a previous installation perfectly fine. However, I'm uncertain why this is happening.`

I'm on (Armbian) Ubuntu Kinetic.

**To Reproduce**
1. Launch kiauh
2. Install KlipperScreen

**Logfile**
```
Installed Misc packages
Creating virtual environment
created virtual environment CPython3.10.7.final.0-64 in 483ms
  creator CPython3Posix(dest=/home/chris/.KlipperScreen-env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/chris/.local/share/virtualenv)
    added seed packages: pip==22.2, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Collecting jinja2==3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
hCollecting netifaces==0.11.0
  Using cached netifaces-0.11.0.tar.gz (30 kB)
ub
  Preparing metadata (setup.py) ... done
Collecting requests==2.28.1
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting websocket-client==1.4.2
  Using cached websocket_client-1.4.2-py3-none-any.whl (55 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 268, in __init__
    cache_entry = factory.get_wheel_cache_entry(link, name)
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 540, in get_wheel_cache_entry
    return self._wheel_cache.get_cache_entry(
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_internal/cache.py", line 262, in get_cache_entry
    return CacheEntry(retval, persistent=True)
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_internal/cache.py", line 214, in __init__
    self.origin = DirectUrl.from_json(origin_direct_url_path.read_text())
  File "/home/chris/.KlipperScreen-env/lib/python3.10/site-packages/pip/_internal/models/direct_url.py", line 206, in from_json
    return cls.from_dict(json.loads(s))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: pip install exited with status code 0
Unable to install dependencies, aborting install.

#=======================================================#
 KlipperScreen installation failed!
#=======================================================#
```

**Comment by alfrix** [comment]
dependencies failing to install are not bugs of KlipperScreen

try:
```
source ~/.KlipperScreen-env/bin/activate
pip install --upgrade pip setuptools wheel
deactivate
```
and reinstall

**Comment by alfrix** [comment]
this error come from dependencies, is not a bug of ks, i cannot do anything about it
"solutions" install an older dependency temporarily until the they fix their issue or try another distro
