### ISSUE TITLE
KlipperScreen failed to load gcode_macros panel [BUG]

### ISSUE THREAD

**Issue by voland696** [jordanruthe/KlipperScreen#860]
**Describe the bug**
[BUG] KlipperScreen failed to load gcode_macros panel

**To Reproduce**
1. Go to Main Menu (BTT PiTFT50)
2. Click on 'Macros Shortcut'
4. See empty page

**Expected behavior**
Expected to see list of macros

**Screenshots**
![macros](https://user-images.githubusercontent.com/527847/209425538-fbaba630-33fc-4f4d-968c-7ba1543f7151.jpg)

**Logfile**
[KlipperScreen.log](https://github.com/jordanruthe/KlipperScreen/files/10298144/KlipperScreen.log)

**Comment by voland696** [comment]
Issue appears on multiple printers.
2022-12-24 06:27:25,825 [screen.py:_load_panel()] - Loading panel: gcode_macros
2022-12-24 06:27:25,825 [screen.py:_load_panel()] - Panel path: /home/pi/KlipperScreen/panels/gcode_macros.py
2022-12-24 06:27:25,859 [screen.py:attach_panel()] - Current panel hierarchy: main_panel > gcode_macros
2022-12-24 06:27:25,931 [screen.py:show_panel()] - Error attaching panel:
'bool' object is not subscriptable
Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 293, in show_panel
    self.attach_panel(panel_name)
  File "/home/pi/KlipperScreen/screen.py", line 306, in attach_panel
    self.panels[panel_name].activate()
  File "/home/pi/KlipperScreen/panels/gcode_macros.py", line 52, in activate
    self.reload_macros()
  File "/home/pi/KlipperScreen/panels/gcode_macros.py", line 127, in reload_macros
    self.load_gcode_macros()
  File "/home/pi/KlipperScreen/panels/gcode_macros.py", line 140, in load_gcode_macros
    self.add_gcode_macro(macro)
  File "/home/pi/KlipperScreen/panels/gcode_macros.py", line 86, in add_gcode_macro
    gcode = self._printer.get_config_section(f"gcode_macro {macro}")["gcode"].split("\n")
TypeError: 'bool' object is not subscriptable

**Comment by voland696** [comment]
Ok, I found that KlipperScreen failed to load gcode_macros panel if there is an extra space in macro definition,
For instance:   [gcode_macro  M1xxx] instead of [gcode_macro M1xxx]
So issue is resolved.
