### ISSUE TITLE
Failed to load shared library 'libgtk-3.so.0' referenced by the typelib: /lib/arm-linux-gnueabihf/libgtk-3.so.0

### ISSUE THREAD

**Issue by DocKuro** [jordanruthe/KlipperScreen#920]
KlipperScreen starts, but the output is not displayed on the external screen.
I have Klipper with Fluidd from a FluiddPi image installed on a Raspberry Pi 4 connected to the printer via UART.
The screen is a Google Nexus 7 tablet, running Lineage OS 14.1, connected to the Pi via USB.
Xserver XSDL has been freshly reinstalled, configuration reset to default; debug mode is enabled and ADB is installed on Pi.
I have tried to uninstall and reinstall KlipperScreen without success.
The screen displays like this: 
![PXL_20230308_154128628](https://user-images.githubusercontent.com/3243007/224289142-057f2292-e7ea-4b0f-8044-70bac93a7d18.jpg)
I have no KlipperScreen.log, but the `journalctl -xe -u KlipperScreen.service` command returns this log upon every restart:
```
-- Automatic restarting of the unit KlipperScreen.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Mar 10 11:13:23 fluiddpi systemd[1]: Stopped KlipperScreen.
-- Subject: A stop job for unit KlipperScreen.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit KlipperScreen.service has finished.
--
-- The job identifier is 468686 and the job result is done.
Mar 10 11:13:23 fluiddpi systemd[1]: Started KlipperScreen.
-- Subject: A start job for unit KlipperScreen.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit KlipperScreen.service has finished successfully.
--
-- The job identifier is 468686.
Mar 10 11:13:23 fluiddpi KlipperScreen-start.sh[11707]: Running /home/pi/KlipperScreen/scripts/launch_KlipperScreen.sh
Mar 10 11:13:23 fluiddpi KlipperScreen-start.sh[11707]: * daemon not running; starting now at tcp:5037
Mar 10 11:13:26 fluiddpi KlipperScreen-start.sh[11707]: * daemon started successfully
Mar 10 11:13:28 fluiddpi KlipperScreen-start.sh[11707]: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=x.org.server/.MainActivity }
Mar 10 11:13:28 fluiddpi KlipperScreen-start.sh[11707]: Warning: Activity not started, its current task has been brought to the front
Mar 10 11:13:29 fluiddpi KlipperScreen-start.sh[11707]: Waiting for x-server to be ready .
Mar 10 11:13:30 fluiddpi python[11743]: Failed to load shared library 'libgtk-3.so.0' referenced by the typelib: /lib/arm-linux-gnueabihf/libgtk-3.so.0: undefined symbol:
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]: Traceback (most recent call last):
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "/home/pi/KlipperScreen/screen.py", line 15, in <module>
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:     from gi.repository import Gtk, Gdk, GLib, Pango
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "/home/pi/.KlipperScreen-env/lib/python3.7/site-packages/gi/importer.py", line 150, in load_module
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:     dynamic_module = load_overrides(introspection_module)
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "/home/pi/.KlipperScreen-env/lib/python3.7/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:     override_mod = importlib.import_module(override_package_name)
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "/home/pi/.KlipperScreen-env/lib/python3.7/importlib/__init__.py", line 127, in import_module
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "/home/pi/.KlipperScreen-env/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 111, in <module>
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:     class Widget(Gtk.Widget):
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "/home/pi/.KlipperScreen-env/lib/python3.7/site-packages/gi/module.py", line 168, in __getattr__
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:     interfaces = tuple(interface for interface in get_interfaces_for_object(info)
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "/home/pi/.KlipperScreen-env/lib/python3.7/site-packages/gi/module.py", line 94, in get_interfaces_for_object
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:     interfaces.append(getattr(module, name))
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "/home/pi/.KlipperScreen-env/lib/python3.7/site-packages/gi/overrides/__init__.py", line 32, in __getattr__
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:     return getattr(self._introspection_module, name)
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "/home/pi/.KlipperScreen-env/lib/python3.7/site-packages/gi/module.py", line 207, in __getattr__
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:     wrapper = metaclass(name, bases, dict_)
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:   File "/home/pi/.KlipperScreen-env/lib/python3.7/site-packages/gi/types.py", line 247, in __init__
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]:     register_interface_info(cls.__info__.get_g_type())
Mar 10 11:13:30 fluiddpi KlipperScreen-start.sh[11707]: TypeError: must be an interface
Mar 10 11:13:30 fluiddpi systemd[1]: KlipperScreen.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit KlipperScreen.service has successfully entered the 'dead' state.
Mar 10 11:13:31 fluiddpi systemd[1]: KlipperScreen.service: Service RestartSec=1s expired, scheduling restart.
Mar 10 11:13:31 fluiddpi systemd[1]: KlipperScreen.service: Scheduled restart job, restart counter is at 201.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Automatic restarting of the unit KlipperScreen.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Mar 10 11:13:31 fluiddpi systemd[1]: Stopped KlipperScreen.
-- Subject: A stop job for unit KlipperScreen.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit KlipperScreen.service has finished.
--
-- The job identifier is 468743 and the job result is done.
Mar 10 11:13:31 fluiddpi systemd[1]: Started KlipperScreen.
-- Subject: A start job for unit KlipperScreen.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit KlipperScreen.service has finished successfully.
--
-- The job identifier is 468743.
lines 1595-1676/1676 (END)
```

**Comment by alfrix** [comment]
not a klipperscreen bug, it's an issue with the OS, you may have missing or corrupt packages, you may solve it with a reinstall or change to the recommended raspberry os lite
