### ISSUE TITLE
Klipperscrren won't launch after last update

### ISSUE THREAD

**Issue by frmelle** [jordanruthe/KlipperScreen#980]
Hi all.

Since last update, I am stuck to a loop, the screen displays the console, tries to launch Klipperscreen then blackscreen and bat to the console.

I am french so fluid is configured in French (that may help to diagnose the problem ...)

Here are my versions :
- fluidd v1.24.0
- klipper v0.11.0-200-g7511151a
- KlipperScreen v0.3.2-37-g1ab9b96
- moonraker v0.8.0-40-gb21f177

Here is what I have on the logs :

```
2023-05-18 00:25:31,536 [screen.py:main()] - Failed to initialize window
Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 1009, in main
    win = KlipperScreen(args, version)
  File "/home/pi/KlipperScreen/screen.py", line 110, in __init__
    self._config = KlipperScreenConfig(configfile, self)
  File "/home/pi/KlipperScreen/ks_includes/config.py", line 108, in __init__
    self.create_translations()
  File "/home/pi/KlipperScreen/ks_includes/config.py", line 116, in create_translations
    self.langs[lng] = gettext.translation('KlipperScreen', localedir=lang_path, languages=[lng], fallback=True)
  File "/usr/lib/python3.7/gettext.py", line 548, in translation
    t = _translations.setdefault(key, class_(fp))
  File "/usr/lib/python3.7/gettext.py", line 260, in __init__
    self._parse(fp)
  File "/usr/lib/python3.7/gettext.py", line 421, in _parse
    catalog[str(msg, charset)] = str(tmsg, charset)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
2023-05-18 00:25:31,539 [screen.py:<module>()] - Fatal error in main loop:
Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 1009, in main
    win = KlipperScreen(args, version)
  File "/home/pi/KlipperScreen/screen.py", line 110, in __init__
    self._config = KlipperScreenConfig(configfile, self)
  File "/home/pi/KlipperScreen/ks_includes/config.py", line 108, in __init__
    self.create_translations()
  File "/home/pi/KlipperScreen/ks_includes/config.py", line 116, in create_translations
    self.langs[lng] = gettext.translation('KlipperScreen', localedir=lang_path, languages=[lng], fallback=True)
  File "/usr/lib/python3.7/gettext.py", line 548, in translation
    t = _translations.setdefault(key, class_(fp))
  File "/usr/lib/python3.7/gettext.py", line 260, in __init__
    self._parse(fp)
  File "/usr/lib/python3.7/gettext.py", line 421, in _parse
    catalog[str(msg, charset)] = str(tmsg, charset)
UnicodeDecodeError:` 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 1020, in <module>
    main()
  File "/home/pi/KlipperScreen/screen.py", line 1012, in main
    raise RuntimeError from e
RuntimeError
```

I looked for non standard characters on my config files but there are none. The command used was `grep --color -P "[\x81-\xff]" *`

This is my first Bug Report so I hope I did well ...

**Comment by alfrix** [comment]
#979
